# Introdução

**Como usar as funções criadas?**

Para importar o pacote *aurum*, primeiramente é preciso executar o snippet abaixo:

```
import os
import sys

module_path = os.path.abspath(os.path.join('..'))

if module_path not in sys.path:
    sys.path.append(module_path)
```

In [1]:
# Antes de executar a célula tomamos um erro:
import aurum

ModuleNotFoundError: No module named 'aurum'

In [2]:
import os
import sys

module_path = os.path.abspath(os.path.join('..'))

if module_path not in sys.path:
    sys.path.append(module_path)

In [3]:
# Após a execução o módulo é importado
import aurum

Agora é só utilizar!

Dica: se estiver utilizando o VSCode ao passar o mouse por cima da função, a documentação aparece com a descrição de cada função.

In [4]:
data = aurum.data.get_ohlcv('PETR4.SA')

In [5]:
data.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,LEAK_Retorno,Alvo
0,2017-01-02,7.373270,7.403488,7.353124,7.383342,7525700,0.0,0,0.043705,1
1,2017-01-03,7.529399,7.881946,7.529399,7.806401,39947800,0.0,0,-0.001292,0
2,2017-01-04,7.781219,7.897056,7.710710,7.806401,37071700,0.0,0,0.010217,1
3,2017-01-05,7.907126,8.012890,7.866835,7.932308,47586300,0.0,0,0.009434,1
4,2017-01-06,7.947417,8.017927,7.806398,7.886981,25592000,0.0,0,0.001275,1

In [6]:
data = aurum.ft.wiki_indicators('Petrobras', data)

In [7]:
data.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,LEAK_Retorno,Alvo,WIKI_daily_views,WIKI_SMA_5,WIKI_SMA_5_Distance,WIKI_Yesterday_diff,WIKI_ROC_5
0,2017-01-02,7.373270,7.403488,7.353124,7.383342,7525700,0.0,0,0.043705,1,230,NaN,NaN,-65.0,NaN
1,2017-01-03,7.529399,7.881946,7.529399,7.806401,39947800,0.0,0,-0.001292,0,295,NaN,NaN,-82.0,NaN
2,2017-01-04,7.781219,7.897056,7.710710,7.806401,37071700,0.0,0,0.010217,1,377,NaN,NaN,100.0,NaN
3,2017-01-05,7.907126,8.012890,7.866835,7.932308,47586300,0.0,0,0.009434,1,277,NaN,NaN,-27.0,NaN
4,2017-01-06,7.947417,8.017927,7.806398,7.886981,25592000,0.0,0,0.001275,1,304,296.6,7.4,-200.0,102.494943